### ISSUE TITLE
ColdBrew isn't enabled after a restart

### ISSUE THREAD

**Issue by paulyoung** [keith/ColdBrew#1]
I'm not sure if this is actually a feature, but is "Open At Login" supposed to actually "enable" ColdBrew or just open it?

I have that preference checked, but after restarting (with ColdBrew enabled beforehand) it's in my dock but the icon is dim and my computer doesn't stay awake.

**Comment by keith** [comment]
Right now it always launches as "off" https://github.com/keith/ColdBrew/blob/master/ColdBrew/AppDelegate.m#L23

We could add this as a feature though!

**Comment by keith** [comment]
Let me know if you're still interested in this. I'm going through and cleaning up old issues. I'd be happy for a PR in this direction but I haven't touched this project much lately.
